#!/usr/bin/env bash
set -euo pipefail

export REFERENCE_REPO_ROOT="${REFERENCE_REPO_ROOT:?Set REFERENCE_REPO_ROOT to the reference backend root}"
export REFERENCE_BACKEND_HOST="${REFERENCE_BACKEND_HOST:-127.0.0.1}"
export REFERENCE_BACKEND_PORT="${REFERENCE_BACKEND_PORT:-2460}"
export REFERENCE_BACKEND_URL="http://${REFERENCE_BACKEND_HOST}:${REFERENCE_BACKEND_PORT}"

