import type { ClusterPeerStatus, ClusterStatus } from '../../shared/types';

export const emptyClusterPeerStatus: ClusterPeerStatus = {
  site_id: '',
  address: '',
  state: 'disconnected',
  role: 'follower',
  match_index: 0,
  replication_lag_entries: 0,
  consecutive_heartbeat_failures: 0,
  consecutive_probe_failures: 0,
  ingress_accepted_batches: 0,
  ingress_rejected_batches: 0,
  ingress_accepted_wire_bytes: 0,
  ingress_rejected_wire_bytes: 0,
  ingress_rejected_batch_too_large: 0,
  ingress_rejected_backpressure: 0,
  ingress_rejected_inflight_wire_budget: 0,
  ingress_rejected_handshake_auth: 0,
  ingress_rejected_handshake_schema: 0,
  ingress_rejected_invalid_wire_batch: 0,
  ingress_rejected_entry_limit: 0,
  ingress_rejected_rate_limit: 0,
  ingress_rejected_apply_batch: 0,
  ingress_rejected_ingress_protocol: 0,
  ingress_last_wire_batch_bytes: 0,
  ingress_total_apply_duration_ms: 0,
  ingress_last_apply_duration_ms: 0,
  ingress_max_apply_duration_ms: 0,
  ingress_apply_duration_ewma_ms: 0,
  ingress_apply_duration_samples: 0,
  ingress_total_replication_latency_ms: 0,
  ingress_last_replication_latency_ms: 0,
  ingress_max_replication_latency_ms: 0,
  ingress_replication_latency_ewma_ms: 0,
  ingress_replication_latency_samples: 0,
  ingress_inflight_wire_batches: 0,
  ingress_inflight_wire_batches_peak: 0,
  ingress_inflight_wire_bytes: 0,
  ingress_inflight_wire_bytes_peak: 0,
  last_heartbeat_at: null,
  last_probe_at: null,
  last_probe_duration_ms: null,
  last_probe_error: null,
  last_ingress_rejection_at: null,
  last_ingress_rejection_reason: null,
  last_ingress_rejection_error: null,
  discovered_via: 'manual',
};

export const emptyClusterStatus: ClusterStatus = {
  enabled: false,
  site_id: '',
  cluster_name: '',
  role: 'standalone',
  term: 0,
  commit_index: 0,
  leader_id: null,
  peers: [],
  replication_lagging_peers: 0,
  replication_lag_total_entries: 0,
  replication_lag_max_entries: 0,
  replication_lag_avg_entries: 0,
  replication_lag_ewma_entries: 0,
  replication_lag_ewma_samples: 0,
  replication_lag_alert_threshold_entries: 0,
  replication_lag_alert_sustained_refreshes: 0,
  replication_lag_alert_streak: 0,
  replication_lag_alert_active: false,
  replication_lag_last_alert_at: null,
  ingress_socket_accept_failures: 0,
  ingress_socket_accepted_connections: 0,
  ingress_socket_completed_connections: 0,
  ingress_socket_failed_connections: 0,
  ingress_socket_active_connections: 0,
  ingress_socket_peak_active_connections: 0,
  ingress_socket_tls_handshake_failures: 0,
  ingress_socket_read_failures: 0,
  ingress_socket_apply_failures: 0,
  ingress_socket_handshake_ack_failures: 0,
  ingress_socket_bytes_read: 0,
  ingress_socket_total_connection_duration_ms: 0,
  ingress_socket_last_connection_duration_ms: 0,
  ingress_socket_max_connection_duration_ms: 0,
  ingress_socket_connection_duration_ewma_ms: 0,
  ingress_socket_connection_duration_le_10ms: 0,
  ingress_socket_connection_duration_le_50ms: 0,
  ingress_socket_connection_duration_le_250ms: 0,
  ingress_socket_connection_duration_le_1000ms: 0,
  ingress_socket_connection_duration_gt_1000ms: 0,
  ingress_socket_max_buffered_bytes: 0,
  ingress_socket_max_queued_frames: 0,
  ingress_socket_max_queued_payload_bytes: 0,
  ingress_socket_paused_read_cycles: 0,
  ingress_socket_paused_read_sleep_ms: 0,
  ingress_socket_last_connection_at: null,
  ingress_socket_last_failure_at: null,
  ingress_socket_last_failure_error: null,
  journal_entries: 0,
  pending_raft_entries: 0,
  last_sync_at: null,
};

export function normalizeClusterStatus(status: unknown): ClusterStatus {
  if (status === null || typeof status !== 'object') {
    return { ...emptyClusterStatus };
  }
  const partialStatus = status as Partial<ClusterStatus>;
  const peers = Array.isArray(partialStatus.peers)
    ? partialStatus.peers.map((peer) => ({
        ...emptyClusterPeerStatus,
        ...(peer && typeof peer === 'object' ? (peer as Partial<ClusterPeerStatus>) : {}),
      }))
    : [];
  return {
    ...emptyClusterStatus,
    ...partialStatus,
    peers,
  };
}
