import type { AppRuntimeState } from '../../shared/types';
import type { AccountsContextValue } from './AccountsContext';
import type { LogsContextValue } from './LogsContext';
import type { NavigationContextValue } from './NavigationContext';
import type { RouterDerivedContextValue } from './RouterDerivedContext';
import type { RuntimeContextValue } from './RuntimeContext';
import type { SessionsContextValue } from './SessionsContext';
import type { SettingsContextValue } from './SettingsContext';

export interface TightropeModel {
  state: AppRuntimeState;
  accounts: AccountsContextValue['accounts'];
  routingModes: SettingsContextValue['routingModes'];
  dashboardSettings: SettingsContextValue['dashboardSettings'];
  firewallMode: SettingsContextValue['firewallMode'];
  firewallEntries: SettingsContextValue['firewallEntries'];
  firewallDraftIpAddress: SettingsContextValue['firewallDraftIpAddress'];
  clusterStatus: SettingsContextValue['clusterStatus'];
  manualPeerAddress: SettingsContextValue['manualPeerAddress'];
  hasUnsavedSettingsChanges: SettingsContextValue['settingsDirty'];
  settingsSaveInFlight: NavigationContextValue['settingsSaveInFlight'];
  settingsLeaveDialogOpen: NavigationContextValue['settingsLeaveDialogOpen'];
  filteredAccounts: AccountsContextValue['filteredAccounts'];
  selectedAccountDetail: AccountsContextValue['selectedAccountDetail'];
  selectedAccountUsage24h: AccountsContextValue['selectedAccountUsage24h'];
  isRefreshingSelectedAccountTelemetry: AccountsContextValue['isRefreshingSelectedAccountTelemetry'];
  isRefreshingSelectedAccountToken: AccountsContextValue['isRefreshingSelectedAccountToken'];
  isRefreshingAllAccountTelemetry: AccountsContextValue['isRefreshingAllAccountTelemetry'];
  trafficClockMs: AccountsContextValue['trafficClockMs'];
  trafficActiveWindowMs: AccountsContextValue['trafficActiveWindowMs'];
  stableSparklinePercents: AccountsContextValue['stableSparklinePercents'];
  formatNumber: AccountsContextValue['formatNumber'];

  setCurrentPage: NavigationContextValue['setCurrentPage'];
  closeSettingsLeaveDialog: NavigationContextValue['closeSettingsLeaveDialog'];
  discardSettingsAndNavigate: NavigationContextValue['discardSettingsAndNavigate'];
  saveSettingsAndNavigate: NavigationContextValue['saveSettingsAndNavigate'];

  setRuntimeAction: RuntimeContextValue['setRuntimeAction'];
  toggleRoutePause: RuntimeContextValue['toggleRoutePause'];
  toggleAutoRestart: RuntimeContextValue['toggleAutoRestart'];
  openBackendDialog: RuntimeContextValue['openBackendDialog'];
  closeBackendDialog: RuntimeContextValue['closeBackendDialog'];
  openAuthDialog: RuntimeContextValue['openAuthDialog'];
  closeAuthDialog: RuntimeContextValue['closeAuthDialog'];
  createListenerUrl: RuntimeContextValue['createListenerUrl'];
  toggleListener: RuntimeContextValue['toggleListener'];
  restartListener: RuntimeContextValue['restartListener'];
  initAuth0: RuntimeContextValue['initAuth0'];
  captureAuthResponse: RuntimeContextValue['captureAuthResponse'];

  setSearchQuery: RouterDerivedContextValue['setSearchQuery'];
  setSelectedAccountId: RouterDerivedContextValue['setSelectedAccountId'];
  setSelectedRoute: RouterDerivedContextValue['setSelectedRoute'];
  setInspectorOpen: RouterDerivedContextValue['setInspectorOpen'];

  openAddAccountDialog: AccountsContextValue['openAddAccountDialog'];
  closeAddAccountDialog: AccountsContextValue['closeAddAccountDialog'];
  setAddAccountStep: AccountsContextValue['setAddAccountStep'];
  selectImportFile: AccountsContextValue['selectImportFile'];
  submitImport: AccountsContextValue['submitImport'];
  simulateBrowserAuth: AccountsContextValue['simulateBrowserAuth'];
  submitManualCallback: AccountsContextValue['submitManualCallback'];
  setManualCallback: AccountsContextValue['setManualCallback'];
  copyBrowserAuthUrl: AccountsContextValue['copyBrowserAuthUrl'];
  copyDeviceVerificationUrl: AccountsContextValue['copyDeviceVerificationUrl'];
  startDeviceFlow: AccountsContextValue['startDeviceFlow'];
  cancelDeviceFlow: AccountsContextValue['cancelDeviceFlow'];
  setAccountSearchQuery: AccountsContextValue['setAccountSearchQuery'];
  setAccountStatusFilter: AccountsContextValue['setAccountStatusFilter'];
  selectAccountDetail: AccountsContextValue['selectAccountDetail'];
  toggleAccountPin: AccountsContextValue['toggleAccountPin'];
  refreshSelectedAccountTelemetry: AccountsContextValue['refreshSelectedAccountTelemetry'];
  refreshSelectedAccountToken: AccountsContextValue['refreshSelectedAccountToken'];
  refreshAllAccountsTelemetry: AccountsContextValue['refreshAllAccountsTelemetry'];
  pauseSelectedAccount: AccountsContextValue['pauseSelectedAccount'];
  reactivateSelectedAccount: AccountsContextValue['reactivateSelectedAccount'];
  deleteSelectedAccount: AccountsContextValue['deleteSelectedAccount'];

  setSessionsKindFilter: SessionsContextValue['setSessionsKindFilter'];
  prevSessionsPage: SessionsContextValue['prevSessionsPage'];
  nextSessionsPage: SessionsContextValue['nextSessionsPage'];
  purgeStaleSessions: SessionsContextValue['purgeStaleSessions'];

  openDrawer: LogsContextValue['openDrawer'];
  closeDrawer: LogsContextValue['closeDrawer'];

  setRoutingMode: SettingsContextValue['setRoutingMode'];
  setStrategyParam: SettingsContextValue['setStrategyParam'];
  setScoringWeight: SettingsContextValue['setScoringWeight'];
  setHeadroomWeight: SettingsContextValue['setHeadroomWeight'];
  setUpstreamStreamTransport: SettingsContextValue['setUpstreamStreamTransport'];
  setStickyThreadsEnabled: SettingsContextValue['setStickyThreadsEnabled'];
  setPreferEarlierResetAccounts: SettingsContextValue['setPreferEarlierResetAccounts'];
  setStrictLockPoolContinuations: SettingsContextValue['setStrictLockPoolContinuations'];
  updateLockedRoutingAccountIds: SettingsContextValue['updateLockedRoutingAccountIds'];
  setOpenaiCacheAffinityMaxAgeSeconds: SettingsContextValue['setOpenaiCacheAffinityMaxAgeSeconds'];
  setImportWithoutOverwrite: SettingsContextValue['setImportWithoutOverwrite'];
  setRoutingPlanModelPricingUsdPerMillion: SettingsContextValue['setRoutingPlanModelPricingUsdPerMillion'];
  setFirewallDraft: SettingsContextValue['setFirewallDraftIpAddress'];
  addFirewallIpAddress: SettingsContextValue['addFirewallIpAddress'];
  removeFirewallIpAddress: SettingsContextValue['removeFirewallIpAddress'];
  toggleSyncEnabled: SettingsContextValue['toggleSyncEnabled'];
  setSyncSiteId: SettingsContextValue['setSyncSiteId'];
  setSyncPort: SettingsContextValue['setSyncPort'];
  setSyncDiscoveryEnabled: SettingsContextValue['setSyncDiscoveryEnabled'];
  setSyncClusterName: SettingsContextValue['setSyncClusterName'];
  setManualPeer: SettingsContextValue['setManualPeerAddress'];
  addManualPeer: SettingsContextValue['addManualPeer'];
  removeSyncPeer: SettingsContextValue['removePeer'];
  setSyncIntervalSeconds: SettingsContextValue['setSyncIntervalSeconds'];
  setSyncConflictResolution: SettingsContextValue['setSyncConflictResolution'];
  setSyncJournalRetentionDays: SettingsContextValue['setSyncJournalRetentionDays'];
  setSyncTlsEnabled: SettingsContextValue['setSyncTlsEnabled'];
  setSyncRequireHandshakeAuth: SettingsContextValue['setSyncRequireHandshakeAuth'];
  setSyncClusterSharedSecret: SettingsContextValue['setSyncClusterSharedSecret'];
  setSyncTlsVerifyPeer: SettingsContextValue['setSyncTlsVerifyPeer'];
  setSyncTlsCaCertificatePath: SettingsContextValue['setSyncTlsCaCertificatePath'];
  setSyncTlsCertificateChainPath: SettingsContextValue['setSyncTlsCertificateChainPath'];
  setSyncTlsPrivateKeyPath: SettingsContextValue['setSyncTlsPrivateKeyPath'];
  setSyncTlsPinnedPeerCertificateSha256: SettingsContextValue['setSyncTlsPinnedPeerCertificateSha256'];
  setSyncSchemaVersion: SettingsContextValue['setSyncSchemaVersion'];
  setSyncMinSupportedSchemaVersion: SettingsContextValue['setSyncMinSupportedSchemaVersion'];
  setSyncAllowSchemaDowngrade: SettingsContextValue['setSyncAllowSchemaDowngrade'];
  setSyncPeerProbeEnabled: SettingsContextValue['setSyncPeerProbeEnabled'];
  setSyncPeerProbeIntervalMs: SettingsContextValue['setSyncPeerProbeIntervalMs'];
  setSyncPeerProbeTimeoutMs: SettingsContextValue['setSyncPeerProbeTimeoutMs'];
  setSyncPeerProbeMaxPerRefresh: SettingsContextValue['setSyncPeerProbeMaxPerRefresh'];
  setSyncPeerProbeFailClosed: SettingsContextValue['setSyncPeerProbeFailClosed'];
  setSyncPeerProbeFailClosedFailures: SettingsContextValue['setSyncPeerProbeFailClosedFailures'];
  triggerSyncNow: SettingsContextValue['triggerSyncNow'];
  openSyncTopologyDialog: SettingsContextValue['openSyncTopology'];
  closeSyncTopologyDialog: SettingsContextValue['closeSyncTopology'];
  setTheme: SettingsContextValue['setTheme'];
  saveSettingsChanges: SettingsContextValue['saveSettings'];
  discardDashboardSettingsChanges: SettingsContextValue['discardSettings'];
}
